---
platform: linux
image: docker:///golang#1.5.4
inputs:
  - name: git-resource
    path: src/github.com/samze/cf-blue-green-deploy
outputs:
  - name: artefacts
run:
    ath: src/github.com/samze/cf-blue-green-deploy/pipeline/ci_build
