---
jobs:
  - name: build
    serial_groups: [version]
    plan:
      - get: bgd-git
        trigger: true
      - get: version
        params: {bump: patch}
      - task: build and test
        file: bgd-git/pipeline/build.yml
      - put: bgd-artefact-swift
        params: {from: artefacts/.*\.tar\.gz}
      - put: version
        params: {file: version/number}
  - name: acceptance
    plan:
      - get: bgd-git
        passed: [build]
      - task: acceptance
        config:
          params:
            CF_PASSWORD: {{cf-password}}
          platform: linux
          image: docker:///bluemixgaragelondon/golangcf:1.5
          inputs:
            - name: bgd-git
              path: src/github.com/samze/cf-blue-green-deploy
          run:
              path: src/github.com/samze/cf-blue-green-deploy/pipeline/ci_acceptance

resources:
- name: bgd-git
  type: git
  source:
    uri: https://github.com/samze/cf-blue-green-deploy

- name: version
  type: semver
  source:
    initial_version: "1.0.6"
    driver: swift
    openstack:
      container: bgd-version
      item_name: version
      region: dallas
      identity_endpoint: https://lon-identity.open.softlayer.com/v3
      domain_name: "884793"
      username: Admin_59b0cc6a2d2ecf5582604b7719de479daa567470
      password: {{swift-password}}

- name: bgd-artefact-swift
  type: swift
  source:
    username: Admin_59b0cc6a2d2ecf5582604b7719de479daa567470
    api_key: {{swift-password}}
    auth_url: https://lon-identity.open.softlayer.com/v3
    domain: "884793"
    container: bgd-artefacts
    regex: blue-green-deploy-([.0-9])+\.tar\.gz
    region: #Resource does not support regions, defaults to dallas

resource_types:
- name: swift
  type: docker-image
  source:
    repository: databus23/concourse-swift-resource
