---
jobs:
  - name: build
    serial_groups: [version]
    plan:
      - get: git-resource
        trigger: true
      - get: version
        params: {bump: patch}
      - task: build and test
        file: git-resource/pipeline/build.yml

resources:
- name: git-resource
  type: git
  source:
    uri: https://github.com/samze/cf-blue-green-deploy
- name: version
  type: semver
  source:
    initial_version: "1.0.6"
    driver: swift
    openstack:
      container: bgd-version
      item_name: version
      region: dallas
      identity_endpoint: https://lon-identity.open.softlayer.com/v3
      domain_name: "884793"
      username: Admin_59b0cc6a2d2ecf5582604b7719de479daa567470
      password: {{swift-password}}
