---
jobs:
  - name: build
    plan:
      - get: git-resource
        trigger: true
      - task: build and test
        file: git-resource/pipeline/build.yml

resources:
- name: git-resource
  type: git
  source:
    uri: https://github.com/samze/cf-blue-green-deploy
